lesson2
976Evill/geekshop pull request #3
Opened 2021-06-02 19:45 UTC by 976Evill

2021-06-03 07:17 UTC, Vokler requested changes

2021-06-03 07:17 UTC, Vokler commented on pruducts/views.py
> +    context = {'title': 'GeekShop - Каталог'}
Добавьте сюда список продуктов - products, и преобразуйте таким образом products.html, удалив от туда повторяющиеся блоки с продуктами, оставив один блок в цикле for

2021-06-04 14:53 UTC, 976Evill commented on pruducts/views.py
> +    context = {'title': 'GeekShop - Каталог'}
Исправил. Сможете принять?

2021-06-04 18:25 UTC, Vokler approved these changes

2021-06-04 18:25 UTC, merged